name: Linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        os: [ ubuntu-latest , macos-latest, windows-latest ]
        node-version: [ 18.x ]
#    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm rin build prod
      - name: linting typescript
        run: npm rin lint:ts
      - name: linting css
        run: npm rin lint:scss
      - name: unit testing
        run: npm rin test:unit
